# Generated by Django 4.0.1 on 2022-02-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentApp', '0002_sufyan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sufyan',
        ),
    ]
