# Generated by Django 4.0.1 on 2022-04-16 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pTitle', models.CharField(blank=True, default='sample_destination', max_length=25, null=True)),
                ('pLocation', models.CharField(blank=True, default='sample_destination', max_length=25, null=True)),
                ('pdetails', models.CharField(blank=True, default='sample_destination', max_length=25, null=True)),
                ('pic', models.CharField(blank=True, default='sample_destination', max_length=25, null=True)),
                ('pCategory', models.TextField(blank=True, default='no category provided !', max_length=518)),
                ('amount', models.PositiveIntegerField(default=100000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
