# Generated by Django 4.0.1 on 2022-04-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SignupApp', '0001_initial'),
        ('TravelRecommendationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamdestination',
            name='user',
        ),
        migrations.AddField(
            model_name='dreamdestination',
            name='tms_owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='SignupApp.tmsuser'),
        ),
    ]
