# Generated by Django 4.0.1 on 2022-04-16 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TravelRecommendationApp', '0002_remove_dreamdestination_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamdestination',
            name='tms_owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
