# Generated by Django 4.0.1 on 2022-04-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelRecommendationApp', '0004_recommendeddestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamdestination',
            name='drm_dest_rigistered',
            field=models.BooleanField(default=False),
        ),
    ]
