# Generated by Django 4.0.1 on 2022-04-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravelRecommendationApp', '0005_dreamdestination_drm_dest_rigistered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendedDestination',
            new_name='RecommendedDestination_cat',
        ),
        migrations.CreateModel(
            name='RecommendedDestination_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pTitle', models.CharField(blank=True, default='sample_destination', max_length=25, null=True)),
                ('pLocation', models.CharField(blank=True, default='sample_destination', max_length=25, null=True)),
                ('pdetails', models.CharField(blank=True, default='sample_destination', max_length=25, null=True)),
                ('pic', models.CharField(blank=True, default='sample_destination', max_length=25, null=True)),
                ('pCategory', models.TextField(blank=True, default='no category provided !', max_length=518)),
                ('amount', models.PositiveIntegerField(default=100000)),
                ('recommendation_template', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TravelRecommendationApp.dreamdestination')),
            ],
        ),
    ]
