# Generated by Django 4.0.1 on 2022-04-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='PCategory',
            field=models.TextField(blank=True, default='No Category Given', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='pLocation',
            field=models.CharField(default='no location given', max_length=50),
        ),
    ]
