# Generated by Django 4.0.1 on 2022-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0002_alter_packagedetails_pcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='PCategory',
            field=models.TextField(blank=True, default='no package details provided !', max_length=518),
        ),
    ]
