# Generated by Django 4.0.1 on 2022-04-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0004_remove_packagedetails_pcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='amount',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
