# Generated by Django 4.0.1 on 2022-04-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0007_rename_packagedetails_packagedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetail',
            name='ptags',
            field=models.TextField(blank=True, default='no tags provided !', max_length=518),
        ),
    ]
